### ISSUE TITLE
iOS Adapter for SDK 7

### ISSUE THREAD

**Issue by koenpunt** [flurry/flurry-adapter-admob-ios#3]
There's currently no adapter for the latest version of the SDK.

Any sight on when there will be one?

**Comment by ugonna** [comment]
A newer version of the adapter is being worked on. No exact ETA yet, but it should be out soon.

**Comment by koenpunt** [comment]
For now it appears to be wording with the v6 adapter, but an official release would be nice

**Comment by ugonna** [comment]
There was an update a while back, but I forgot to update this thread. Closing. Thanks.
