### ISSUE TITLE
podfile 

### ISSUE THREAD

**Issue by dklt** [flurry/flurry-adapter-admob-ios#4]
pod instructions on main landing page no long works....

I pod search adapter found the new name -->  "AdMobMediationAdapterFlurry"

-> AdMobMediationAdapterFlurry (7.6.3)
   Flurry adapter for Google Ads SDK
   pod 'AdMobMediationAdapterFlurry', '~> 7.6.3'
   - Homepage: https://developer.yahoo.com/flurry
   - Source:   https://github.com/flurry/flurry-adapter-admob-ios.git
   - Versions: 7.6.3 [master repo]

FYI

**Comment by ugonna** [comment]
Thanks, @dklt. The docs will be updated.
