### ISSUE TITLE
Library BitCode Issue

### ISSUE THREAD

**Issue by hf2186** [flurry/flurry-adapter-admob-ios#5]
AdMobMediationAdapterFlurry/FlurryAdapter/libFlurryAdapter.a(GADMAdapterFlurryAppCircle.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by eysteinbye** [comment]
I get the same error. Anyone found a solution to this?

**Comment by hf2186** [comment]
@ugonna is there an ETA for the fix?

**Comment by ugonna** [comment]
Hi @hf2186 and @eysteinbye. Thanks for reporting this. We're taking a look at this and a scheduled release for this week should take care of it.

**Comment by ugonna** [comment]
This should be resolved with [v7.9.2](https://cocoapods.org/pods/AdMobMediationAdapterFlurry). Let us know if there are any other issues.

**Comment by eysteinbye** [comment]
7.9.2 Works 👍  Thank you @ugonna

**Comment by hf2186** [comment]
Confirmed 7.9.2 works. Thanks!
